export interface SalesforceProductRecord {
  id: string;
  ownerId: string;
  isDeleted: boolean;
  name: string;
  createdDate: string;
  createdById: string;
  lastModifiedDate: string;
  lastModifiedById: string;
  systemModstamp: string;
  lastViewedDate: string | null;
  lastReferencedDate: string | null;
  careProgramEnrolleeId: string | null;
  careProgramProductId: string | null;
  careProgramProviderId: string | null;
  status: string | null;
  sourceSystemIdentifier: string | null;
  sourceSystem: string | null;
  clinical_Trial_Program__c: string | null;
  cordella_ID__c: string | null;
  cuff_Size__c: string | null;
  expiration_Date__c: string | null;
  first_Home_Use_Date__c: string | null;
  five_Year_End_of_Useful_Life_Date__c: string | null;
  four_Year_End_of_Useful_Life_Date__c: string | null;
  imeI__c: string | null;
  is_Visible_on_Patient_Card__c: boolean;
  lot__c: string | null;
  patient_Account__c: string | null;
  product_Code__c: string | null;
  product_Name__c: string | null;
  product_Record_Type__c: string | null;
  serial_Number__c: string | null;
  setup_Date__c: string | null;
  ship_Date__c: string | null;
  software_Version__c: string | null;
  two_Year_End_of_Useful_Life_Date__c: string | null;
  is_Replacement_Product__c: boolean;
  inventory_From_Site__c: string | null;
  parent_Product__c: string | null;
  rmA__c: string | null;
  reader_Kit_Product__c: string | null;
  implant_Case_Report__c: string | null;
  number_of_RMAs__c: number | null;
  rmA_Case__c: string | null;
}
